# Conclusões {#sec-conclusion}

Este trabalho teve o objetivo de avaliar o nível das informações nos portais dos Detrans de todo o país, buscando entender como essas instituições trabalham e disponibilizam informações e serviços de interesse público. 

A avaliação foi baseada em sete categorias. Em quatro delas - frota de veículos, condutores habilitados, infrações e sinistros de trânsito - a avaliação foi baseada na qualidade, variedade e disponibilidade de dados estatísticos, com base em três critérios: *Periodicidade*, *Interatividade* e *Nível de desagregação*. Em outras três categorias - atendimento ao público, educação para o trânsito e centro de formação de condutores - a avaliação foi realizada com critérios mais específicos de disponibilidade de informações para o público, sendo que algumas dessas categorias não apresentam dados estritamente estatísticos.

Em uma verificação preliminar, observou-se que apenas 9 portais de Detrans contêm informações de todas as categorias consideradas, ou seja, um em cada três dos sites visitados. Doze UFs não disponibilizam dados sobre sinistros de trânsito, ou seja, nesses locais, uma das informações mais importantes para o diagnóstico da segurança viária não está disponível para o público.

Observando as notas finais, destaca-se os Detrans com as melhores práticas: Detran-SE (nota 9,6), Detran-SP (nota 9,3) e Detran-ES (nota 8,9). Entre 2020 e 2024, os portais de 17 Detrans apresentaram uma melhoria no desempenho, mostrando que mais da metade dos portais disponíveis no país vem demonstrando evoluções positivas.

Essa pesquisa incluiu métodos e resultados importantes para a análise sistemática dos portais dos Detrans, levando em consideração o nível de divulgação de dados e serviços de importância para o desenvolvimento da mobilidade segura. Como próximos passos, entende-se a necessidade de aplicar novamente essa análise, assim obtendo informações mais precisas sobre a evolução de desempenho quando se considera a disponibilização de dados. Em adição, considera-se a necessidade de aprimorar os métodos aqui apresentados, levando a discussão para o poder público e também para a sociedade civil.